### PR TITLE
Better Chunks at decode + strength value

### PR DESCRIPTION
**Pull request by XmYx**
This PR makes chunk mechanism at decode effective, and exposes sampling strength for the init latent (0.0 defaults it to None as originally)

### CODE REVIEW

**Comment by kabachuha** [comment]
Heey! The first step for video2video

**Comment by kabachuha** [comment]
Testing your PR right now, btw

**Review by kabachuha — APPROVED** [review]
All seems to work fine, tested both in normal mode and on cpu

**Comment by XmYx** [comment]
> Testing your PR right now, btw

Neat! Did we add control for the strength yet tho? This should be great fun with Logan's pr..

**Comment by kabachuha** [comment]
I guess those two values are connected, just they are in the original Stable Diffusion, where the number of img2img steps = max steps * denoising_strength

**Pull request merged**
