### PR TITLE
fix for loading checkpoint on mps

### PR DESCRIPTION
**Pull request by kabachuha**

### CODE REVIEW

**Comment by kabachuha** [comment]
@doricem check it out

**Comment by doricem** [comment]
Thank you. I'm getting this when I try to update extensions. .. 

```Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 8.8s (import gradio: 1.0s, import ldm: 0.4s, other imports: 0.8s, load scripts: 0.5s, load SD checkpoint: 2.0s, create ui: 4.0s).
Error checking updates for deforum:
Traceback (most recent call last):
  File "/Users/bsath/stable-diffusion-webui/modules/ui_extensions.py", line 66, in check_updates
    ext.check_updates()
  File "/Users/bsath/stable-diffusion-webui/modules/extensions.py", line 69, in check_updates
    for fetch in repo.remote().fetch(dry_run=True):
  File "/Users/bsath/stable-diffusion-webui/venv/lib/python3.10/site-packages/git/remote.py", line 1007, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
  File "/Users/bsath/stable-diffusion-webui/venv/lib/python3.10/site-packages/git/remote.py", line 861, in _get_fetch_info_from_stderr
    with open(fetch_head.abspath, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/bsath/stable-diffusion-webui/extensions/deforum/.git/FETCH_HEAD'
```

**Comment by kabachuha** [comment]
It seems like your `extensions/deforum` isn't cloned properly. Just remove deforum for now and reinstall it from the extensions table later. Anyway, this error is unrelated to the issue

**Comment by doricem** [comment]
Ahhh, I see. Yeah.    
Well, still getting this error

```Exception occured
Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.```

**Comment by kabachuha** [comment]
Won't work, since Conv3D is not supported on MacOs yet

**Pull request closed without merging**
