### PR TITLE
Add vid2vid

### LINKED ISSUE #4: [Feature request] Add video2video mode (with in-painting and outpainting analogues for making vid from keyframes and AI-continuing vids)
Just like stable diffusion is transforming one picture into another one (or noise, if the input is not specified), this model is theoretically capable of transforming a video into another video, using text hints if we initialize the latents with the input video frames

https://github.com/deforum-art/sd-webui-modelscope-text2video/blob/857594d61ea776794296ffa6d256bf93eaa7fcd2/scripts/t2v_pipeline.py#L153

---

The proposed scheme (like img2img, but to videos)

- [ ] Prepare input videos for the input mode (rescaling, cutting to the input length)
- [x] Encode videos to the latent representation by running the VAE
- [x] Configure the DDIM scheduler to use Denoising strength 
- [x] Pass the latents to the pipeline and test it 
- [ ] Bonus: In-framing —pass an input video, add a few keyframes, mask them, fill the rest with latent noise or keep the original, vid2vid diffuse not masked area. Just like in-painting, but for vid2vid
- [ ] Bonus 2: Video continuation — extending the vid with latent noise frames and moving a 'window' making the aforementioned 'in-framing', thus allowing the video to extend beyond vram bounds, but losing some of its temporal coherence

### PR DESCRIPTION
**Pull request by kabachuha**
Things left to do:
- [x] Add the second video2video tab
- [x] Add the drag and drop window for video uploading, autoslice the video to the target format
- [ ] Configure denoising strength influence

Closes #4

### CODE REVIEW

**Comment by ExponentialML** [comment]
Hey! May I ask how close are we to finishing this PR? I can add reading video data to frames, but can open another PR if it will be a blocker.

**Comment by kabachuha** [comment]
Well, we have the tab, but need to consider how to tie img2img steps and denoising strengths

We need to do some tests like figuring out if we can leave out img2img steps at all and just use denoising strength as it's in Auto

**Comment by nagolinc** [comment]
> Well, we have the tab, but need to consider how to tie img2img steps and denoising strengths
> 
> We need to do some tests like figuring out if we can leave out img2img steps at all and just use denoising strength as it's in Auto
> 
> So, really close

we should just be able to do img2img_frames = frames*(1-denoising strength) and drop the img2img_frames parameter

**Comment by kabachuha** [comment]
The UI
image

**Comment by kabachuha** [comment]
Now, the UI is done and the conflicts are solved

The only thing left is to figure out denoising strength influence

**Comment by ExponentialML** [comment]
> Now, the UI is done and the conflicts are solved
> 
> The only thing left is to figure out denoising strength influence

I agree with dropping the the img2img steps in favor of denoising strength (0-1).
Here is some code from a local video diffusion project I was working on that may be beneficial 

*(this was using an init image repeated along the frame dimension, but this can be easily translated here).*
```py

# Step 1
def get_timesteps(self, num_inference_steps, strength, device):
        # get the original timestep using init_timestep
        init_timestep = min(int(num_inference_steps * strength), num_inference_steps)

        t_start = max(num_inference_steps - init_timestep, 0)
        timesteps = self.scheduler.timesteps[t_start:]

        return timesteps, num_inference_steps - t_start

# Step 2
init_timesteps, num_inference_steps = self.get_timesteps(
                    num_inference_steps, 
                    strength, 
                    device
                ) 
# Step 3
def arbitrary_inference_code(self, image):
        b, f = image.shape[0], image.shape[2]
        image = image.to(device=device, dtype=dtype)
        
        image = rearrange(image, 'b c f h w -> (b f) c h w')
        image_latent = self.vae.encode(image).latent_dist.sample(generator)
        image_latent = rearrange(image_latent, '(b f) c h w -> b c f h w', b=b, f=f)
        image_latent = image_latent *  0.18215
        
        timestep = timesteps[:1].repeat(batch_size)
        noise = torch.randn(image_latent.shape, generator=generator, device=device, dtype=dtype)
        image_latent = self.scheduler.add_noise(image_latent, noise, timestep)
        
        return image_latent
```

**Pull request merged**
